version: '3'

services:
  app:
    container_name: node-app
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - NODE_ENV=local
      - NODE_PORT=3000
      - NODE_HOST=0.0.0.0
      - REDIS_HOST=cache
      - REDIS_PORT=6739
      - REDIS_URL=redis://cache
    depends_on:
      - redis
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "."

  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379

